### ISSUE TITLE
Minor tweaks to the README

### ISSUE THREAD

**Issue by pavpanchekha** [nathand8/layout-quickcheck#1]
A couple of small things we could improve in the README:

- [x] Use `pip3` instead of `pip`, on macOS often people have both
- [ ] Worth noting that on macOS both `chromedriver` and `geckodriver` can be installed with `brew install XXX`, and that the Safari webdriver ships by default. And also copy in the `xattr` command you need (below).

The `xattr` command you need is:

```
xattr -d com.apple.quarantine /usr/local/bin/chromedriver
xattr -d com.apple.quarantine /usr/local/bin/geckodriver
```

**Comment by nathand8** [comment]
Done. Can you review the README?

Also, the purpose of `xattr` is lost on me... what is that for?

**Comment by pavpanchekha** [comment]
Some apple stuff

**Comment by pavpanchekha** [comment]
You need it after installing geckodriver / chromedriver

**Comment by nathand8** [comment]
Sounds good. README has been updated with the improvements 👍
